steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'doc-processor'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--set-env-vars'
      - 'HF_TOKEN=your_hf_token_key,GEMINI_API_KEY=you_llm_model key'

options:
  logging: CLOUD_LOGGING_ONLY